# Generated by Django 5.0 on 2024-02-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_in_touch',
            name='message',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
