# Generated by Django 5.0 on 2024-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momosApp', '0002_get_in_touch_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_in_touch',
            name='message',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
